### ISSUE TITLE
Very difficult to use

### ISSUE THREAD

**Issue by macosupdate** [blogdaren/PHPCreeper#3]
Thank you for writing phpcreeper
I want to use it, but it is difficult to use, the manual is not good, I am not Chinese, so I have to translate the document.
I'm a workerman user, it's really easy to use
I followed the instructions in the documentation, http://www.phpcreeper.com/docs/InstallGuide/StartInstall.html
**all the start scripts seem to be disabled, please check the `main` config file**
Even though I turned on true in main.php

**Comment by blogdaren** [comment]
[【1】i have tested it many times by the guide line again and again, then couldn't show the problem u mentioned,  the confiuration for all the start scripts have already been enabled as true by default, it means we need to do nothing else for the first time , so did u changed sth? plz tell me ....  i recommed u'd better  try to checkout the latest version `PHPCreeper` and `PHPCreeper-Application` to run once again following the docs strictly,  contact me if any problem.
【2】for english version docs,  plz rerer to: https://github.com/blogdaren/PHPCreeper
【3】 `PHPCreeper-Application`  app framework is not the necessary option, if u like, you can write business code just like `Workerman` way,   please refer to the english version url address above for detailed usage
