### ISSUE TITLE
关于 guzzlehttp/guzzle 版本兼容问题

### ISSUE THREAD

**Issue by xuewlcn** [blogdaren/PHPCreeper#5]
安装时报错：
blogdaren/phpcreeper[v1.3.0, ..., v1.4.2] require guzzlehttp/guzzle ^6.4 -> found guzzlehttp/guzzle[6.4.0, ..., 6.5.8] but the package is fixed to 7.4.5 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

原因是其它的 composer 包使用了更高版本的 guzzlehttp/guzzle ，想问下 blogdaren/phpcreeper 有没有计划升级依赖的 guzzlehttp/guzzle 版本呢

**Comment by blogdaren** [comment]
更新到最新版 v1.4.3
