### ISSUE TITLE
PredisClient 抛异常， $serverCount = 0

### ISSUE THREAD

**Issue by xuewlcn** [blogdaren/PHPCreeper#6]
Modulo by zero in /app/vendor/blogdaren/phpcreeper/src/Kernel/Middleware/MessageQueue/PredisClient.php:511

**Comment by blogdaren** [comment]
稍候我看下

**Comment by blogdaren** [comment]
暂时无法重现你说的这个问题，所以需要你提供下额外信息：
1.  是基于PHPCreeper-Application框架开发的还是直接以裸worker模式编写的？
2.  贴下redis完整配置（敏感信息你自己屏蔽下）
3.  最好能贴下完整的异常栈

**Comment by xuewlcn** [comment]
发现问题了，是因为改版后 redis 修改为 predis ，配置文件不一样导致

**Comment by blogdaren** [comment]
*  1.4.2+ 版本之后不再使用ext-redis作为默认的redis客户端，而是采用predis作为默认的redis客户端；不过仍然兼容支持切换旧版本的默认redis客户端，方法为：
```
PHPCreeper::setDefaultRedisClient('redis'); 
```
* 按理升级版本之后，配置文件原样不动的话，也不应该出现题示的问题，因为引擎针对不同的客户端均做了redis config兼容处理；另外配置格式唯一变动的地方就是支持配置多个redis实例，即redis config由支持原来的一维数组变为同时支持二维数组，这种情况对于上层开发来说也是无感的。

**Comment by xuewlcn** [comment]
嗯，这个是我得问题，感谢大佬得耐心回复
